// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: migration.proto

package migration

import (
	common "github.com/dell/dell-csi-extensions/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MigrateTypes int32

const (
	MigrateTypes_UNKNOWN_MIGRATE  MigrateTypes = 0
	MigrateTypes_NON_REPL_TO_REPL MigrateTypes = 1
	MigrateTypes_REPL_TO_NON_REPL MigrateTypes = 2
	MigrateTypes_VERSION_UPGRADE  MigrateTypes = 3
)

// Enum value maps for MigrateTypes.
var (
	MigrateTypes_name = map[int32]string{
		0: "UNKNOWN_MIGRATE",
		1: "NON_REPL_TO_REPL",
		2: "REPL_TO_NON_REPL",
		3: "VERSION_UPGRADE",
	}
	MigrateTypes_value = map[string]int32{
		"UNKNOWN_MIGRATE":  0,
		"NON_REPL_TO_REPL": 1,
		"REPL_TO_NON_REPL": 2,
		"VERSION_UPGRADE":  3,
	}
)

func (x MigrateTypes) Enum() *MigrateTypes {
	p := new(MigrateTypes)
	*p = x
	return p
}

func (x MigrateTypes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MigrateTypes) Descriptor() protoreflect.EnumDescriptor {
	return file_migration_proto_enumTypes[0].Descriptor()
}

func (MigrateTypes) Type() protoreflect.EnumType {
	return &file_migration_proto_enumTypes[0]
}

func (x MigrateTypes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MigrateTypes.Descriptor instead.
func (MigrateTypes) EnumDescriptor() ([]byte, []int) {
	return file_migration_proto_rawDescGZIP(), []int{0}
}

// ActionTypes are the exhaustive set of actions which can be performed on
// the migration group
type ActionTypes int32

const (
	// Site-Aware actions
	ActionTypes_UNKNOWN_ACTION ActionTypes = 0
	// Migrate
	ActionTypes_MG_MIGRATE ActionTypes = 1
	// Rescan
	ActionTypes_MG_RESCAN ActionTypes = 2
	// Commit
	ActionTypes_MG_COMMIT ActionTypes = 3
)

// Enum value maps for ActionTypes.
var (
	ActionTypes_name = map[int32]string{
		0: "UNKNOWN_ACTION",
		1: "MG_MIGRATE",
		2: "MG_RESCAN",
		3: "MG_COMMIT",
	}
	ActionTypes_value = map[string]int32{
		"UNKNOWN_ACTION": 0,
		"MG_MIGRATE":     1,
		"MG_RESCAN":      2,
		"MG_COMMIT":      3,
	}
)

func (x ActionTypes) Enum() *ActionTypes {
	p := new(ActionTypes)
	*p = x
	return p
}

func (x ActionTypes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionTypes) Descriptor() protoreflect.EnumDescriptor {
	return file_migration_proto_enumTypes[1].Descriptor()
}

func (ActionTypes) Type() protoreflect.EnumType {
	return &file_migration_proto_enumTypes[1]
}

func (x ActionTypes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionTypes.Descriptor instead.
func (ActionTypes) EnumDescriptor() ([]byte, []int) {
	return file_migration_proto_rawDescGZIP(), []int{1}
}

// Input request used in GetMigrationCapabilities API
type GetMigrationCapabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMigrationCapabilityRequest) Reset() {
	*x = GetMigrationCapabilityRequest{}
	mi := &file_migration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMigrationCapabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMigrationCapabilityRequest) ProtoMessage() {}

func (x *GetMigrationCapabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMigrationCapabilityRequest.ProtoReflect.Descriptor instead.
func (*GetMigrationCapabilityRequest) Descriptor() ([]byte, []int) {
	return file_migration_proto_rawDescGZIP(), []int{0}
}

type MigrationCapability struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*MigrationCapability_Rpc
	Type          isMigrationCapability_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationCapability) Reset() {
	*x = MigrationCapability{}
	mi := &file_migration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationCapability) ProtoMessage() {}

func (x *MigrationCapability) ProtoReflect() protoreflect.Message {
	mi := &file_migration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationCapability.ProtoReflect.Descriptor instead.
func (*MigrationCapability) Descriptor() ([]byte, []int) {
	return file_migration_proto_rawDescGZIP(), []int{1}
}

func (x *MigrationCapability) GetType() isMigrationCapability_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *MigrationCapability) GetRpc() *MigrationCapability_RPC {
	if x != nil {
		if x, ok := x.Type.(*MigrationCapability_Rpc); ok {
			return x.Rpc
		}
	}
	return nil
}

type isMigrationCapability_Type interface {
	isMigrationCapability_Type()
}

type MigrationCapability_Rpc struct {
	Rpc *MigrationCapability_RPC `protobuf:"bytes,1,opt,name=rpc,proto3,oneof"`
}

func (*MigrationCapability_Rpc) isMigrationCapability_Type() {}

// Capabilities of the driver, in terms of the
// RPC calls it supports
type GetMigrationCapabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capabilities  []*MigrationCapability `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMigrationCapabilityResponse) Reset() {
	*x = GetMigrationCapabilityResponse{}
	mi := &file_migration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMigrationCapabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMigrationCapabilityResponse) ProtoMessage() {}

func (x *GetMigrationCapabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMigrationCapabilityResponse.ProtoReflect.Descriptor instead.
func (*GetMigrationCapabilityResponse) Descriptor() ([]byte, []int) {
	return file_migration_proto_rawDescGZIP(), []int{2}
}

func (x *GetMigrationCapabilityResponse) GetCapabilities() []*MigrationCapability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// Information about a specific volume
type Volume struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Size of the volume in bytes
	CapacityBytes int64 `protobuf:"varint,1,opt,name=capacity_bytes,json=capacityBytes,proto3" json:"capacity_bytes,omitempty"`
	// Volume ID - should be the same as one
	// returned in the CSI CreateVolumeResponse
	VolumeId string `protobuf:"bytes,2,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	// Optional context information about the volume
	// which can be passed down to the driver in future calls
	FsType        string            `protobuf:"bytes,3,opt,name=fs_type,json=fsType,proto3" json:"fs_type,omitempty"`
	VolumeContext map[string]string `protobuf:"bytes,4,rep,name=volume_context,json=volumeContext,proto3" json:"volume_context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Volume) Reset() {
	*x = Volume{}
	mi := &file_migration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Volume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Volume) ProtoMessage() {}

func (x *Volume) ProtoReflect() protoreflect.Message {
	mi := &file_migration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Volume.ProtoReflect.Descriptor instead.
func (*Volume) Descriptor() ([]byte, []int) {
	return file_migration_proto_rawDescGZIP(), []int{3}
}

func (x *Volume) GetCapacityBytes() int64 {
	if x != nil {
		return x.CapacityBytes
	}
	return 0
}

func (x *Volume) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *Volume) GetFsType() string {
	if x != nil {
		return x.FsType
	}
	return ""
}

func (x *Volume) GetVolumeContext() map[string]string {
	if x != nil {
		return x.VolumeContext
	}
	return nil
}

type VolumeMigrateRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	VolumeHandle string                 `protobuf:"bytes,1,opt,name=volume_handle,json=volumeHandle,proto3" json:"volume_handle,omitempty"`
	StorageClass string                 `protobuf:"bytes,2,opt,name=storage_class,json=storageClass,proto3" json:"storage_class,omitempty"`
	// Types that are valid to be assigned to MigrateTypes:
	//
	//	*VolumeMigrateRequest_Type
	MigrateTypes       isVolumeMigrateRequest_MigrateTypes `protobuf_oneof:"migrate_types"`
	ScParameters       map[string]string                   `protobuf:"bytes,4,rep,name=sc_parameters,json=scParameters,proto3" json:"sc_parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ScSourceParameters map[string]string                   `protobuf:"bytes,5,rep,name=scSource_parameters,json=scSourceParameters,proto3" json:"scSource_parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ShouldClone        bool                                `protobuf:"varint,6,opt,name=should_clone,json=shouldClone,proto3" json:"should_clone,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VolumeMigrateRequest) Reset() {
	*x = VolumeMigrateRequest{}
	mi := &file_migration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeMigrateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeMigrateRequest) ProtoMessage() {}

func (x *VolumeMigrateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeMigrateRequest.ProtoReflect.Descriptor instead.
func (*VolumeMigrateRequest) Descriptor() ([]byte, []int) {
	return file_migration_proto_rawDescGZIP(), []int{4}
}

func (x *VolumeMigrateRequest) GetVolumeHandle() string {
	if x != nil {
		return x.VolumeHandle
	}
	return ""
}

func (x *VolumeMigrateRequest) GetStorageClass() string {
	if x != nil {
		return x.StorageClass
	}
	return ""
}

func (x *VolumeMigrateRequest) GetMigrateTypes() isVolumeMigrateRequest_MigrateTypes {
	if x != nil {
		return x.MigrateTypes
	}
	return nil
}

func (x *VolumeMigrateRequest) GetType() MigrateTypes {
	if x != nil {
		if x, ok := x.MigrateTypes.(*VolumeMigrateRequest_Type); ok {
			return x.Type
		}
	}
	return MigrateTypes_UNKNOWN_MIGRATE
}

func (x *VolumeMigrateRequest) GetScParameters() map[string]string {
	if x != nil {
		return x.ScParameters
	}
	return nil
}

func (x *VolumeMigrateRequest) GetScSourceParameters() map[string]string {
	if x != nil {
		return x.ScSourceParameters
	}
	return nil
}

func (x *VolumeMigrateRequest) GetShouldClone() bool {
	if x != nil {
		return x.ShouldClone
	}
	return false
}

type isVolumeMigrateRequest_MigrateTypes interface {
	isVolumeMigrateRequest_MigrateTypes()
}

type VolumeMigrateRequest_Type struct {
	Type MigrateTypes `protobuf:"varint,3,opt,name=type,proto3,enum=migration.v1.MigrateTypes,oneof"`
}

func (*VolumeMigrateRequest_Type) isVolumeMigrateRequest_MigrateTypes() {}

type VolumeMigrateResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MigratedVolume *Volume                `protobuf:"bytes,1,opt,name=migrated_volume,json=migratedVolume,proto3" json:"migrated_volume,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VolumeMigrateResponse) Reset() {
	*x = VolumeMigrateResponse{}
	mi := &file_migration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeMigrateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeMigrateResponse) ProtoMessage() {}

func (x *VolumeMigrateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeMigrateResponse.ProtoReflect.Descriptor instead.
func (*VolumeMigrateResponse) Descriptor() ([]byte, []int) {
	return file_migration_proto_rawDescGZIP(), []int{5}
}

func (x *VolumeMigrateResponse) GetMigratedVolume() *Volume {
	if x != nil {
		return x.MigratedVolume
	}
	return nil
}

type ArrayMigrateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ActionTypes:
	//
	//	*ArrayMigrateRequest_Action
	ActionTypes   isArrayMigrateRequest_ActionTypes `protobuf_oneof:"action_types"`
	Parameters    map[string]string                 `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrayMigrateRequest) Reset() {
	*x = ArrayMigrateRequest{}
	mi := &file_migration_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrayMigrateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayMigrateRequest) ProtoMessage() {}

func (x *ArrayMigrateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migration_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrayMigrateRequest.ProtoReflect.Descriptor instead.
func (*ArrayMigrateRequest) Descriptor() ([]byte, []int) {
	return file_migration_proto_rawDescGZIP(), []int{6}
}

func (x *ArrayMigrateRequest) GetActionTypes() isArrayMigrateRequest_ActionTypes {
	if x != nil {
		return x.ActionTypes
	}
	return nil
}

func (x *ArrayMigrateRequest) GetAction() *Action {
	if x != nil {
		if x, ok := x.ActionTypes.(*ArrayMigrateRequest_Action); ok {
			return x.Action
		}
	}
	return nil
}

func (x *ArrayMigrateRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type isArrayMigrateRequest_ActionTypes interface {
	isArrayMigrateRequest_ActionTypes()
}

type ArrayMigrateRequest_Action struct {
	Action *Action `protobuf:"bytes,3,opt,name=action,proto3,oneof"`
}

func (*ArrayMigrateRequest_Action) isArrayMigrateRequest_ActionTypes() {}

type ArrayMigrateResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Types that are valid to be assigned to ActionTypes:
	//
	//	*ArrayMigrateResponse_Action
	ActionTypes   isArrayMigrateResponse_ActionTypes `protobuf_oneof:"action_types"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrayMigrateResponse) Reset() {
	*x = ArrayMigrateResponse{}
	mi := &file_migration_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrayMigrateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayMigrateResponse) ProtoMessage() {}

func (x *ArrayMigrateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migration_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrayMigrateResponse.ProtoReflect.Descriptor instead.
func (*ArrayMigrateResponse) Descriptor() ([]byte, []int) {
	return file_migration_proto_rawDescGZIP(), []int{7}
}

func (x *ArrayMigrateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ArrayMigrateResponse) GetActionTypes() isArrayMigrateResponse_ActionTypes {
	if x != nil {
		return x.ActionTypes
	}
	return nil
}

func (x *ArrayMigrateResponse) GetAction() *Action {
	if x != nil {
		if x, ok := x.ActionTypes.(*ArrayMigrateResponse_Action); ok {
			return x.Action
		}
	}
	return nil
}

type isArrayMigrateResponse_ActionTypes interface {
	isArrayMigrateResponse_ActionTypes()
}

type ArrayMigrateResponse_Action struct {
	Action *Action `protobuf:"bytes,2,opt,name=action,proto3,oneof"`
}

func (*ArrayMigrateResponse_Action) isArrayMigrateResponse_ActionTypes() {}

// SupportedActions is the set of action types
// which are supported by a specific CSI driver
type SupportedActions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Actions:
	//
	//	*SupportedActions_Type
	Actions       isSupportedActions_Actions `protobuf_oneof:"Actions"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupportedActions) Reset() {
	*x = SupportedActions{}
	mi := &file_migration_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportedActions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportedActions) ProtoMessage() {}

func (x *SupportedActions) ProtoReflect() protoreflect.Message {
	mi := &file_migration_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportedActions.ProtoReflect.Descriptor instead.
func (*SupportedActions) Descriptor() ([]byte, []int) {
	return file_migration_proto_rawDescGZIP(), []int{8}
}

func (x *SupportedActions) GetActions() isSupportedActions_Actions {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *SupportedActions) GetType() ActionTypes {
	if x != nil {
		if x, ok := x.Actions.(*SupportedActions_Type); ok {
			return x.Type
		}
	}
	return ActionTypes_UNKNOWN_ACTION
}

type isSupportedActions_Actions interface {
	isSupportedActions_Actions()
}

type SupportedActions_Type struct {
	Type ActionTypes `protobuf:"varint,1,opt,name=type,proto3,enum=migration.v1.ActionTypes,oneof"`
}

func (*SupportedActions_Type) isSupportedActions_Actions() {}

type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionTypes   ActionTypes            `protobuf:"varint,1,opt,name=action_types,json=actionTypes,proto3,enum=migration.v1.ActionTypes" json:"action_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_migration_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_migration_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_migration_proto_rawDescGZIP(), []int{9}
}

func (x *Action) GetActionTypes() ActionTypes {
	if x != nil {
		return x.ActionTypes
	}
	return ActionTypes_UNKNOWN_ACTION
}

type MigrationCapability_RPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MigrateTypes           `protobuf:"varint,1,opt,name=type,proto3,enum=migration.v1.MigrateTypes" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationCapability_RPC) Reset() {
	*x = MigrationCapability_RPC{}
	mi := &file_migration_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationCapability_RPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationCapability_RPC) ProtoMessage() {}

func (x *MigrationCapability_RPC) ProtoReflect() protoreflect.Message {
	mi := &file_migration_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationCapability_RPC.ProtoReflect.Descriptor instead.
func (*MigrationCapability_RPC) Descriptor() ([]byte, []int) {
	return file_migration_proto_rawDescGZIP(), []int{1, 0}
}

func (x *MigrationCapability_RPC) GetType() MigrateTypes {
	if x != nil {
		return x.Type
	}
	return MigrateTypes_UNKNOWN_MIGRATE
}

var File_migration_proto protoreflect.FileDescriptor

const file_migration_proto_rawDesc = "" +
	"\n" +
	"\x0fmigration.proto\x12\fmigration.v1\x1a\fcommon.proto\"\x1f\n" +
	"\x1dGetMigrationCapabilityRequest\"\x8f\x01\n" +
	"\x13MigrationCapability\x129\n" +
	"\x03rpc\x18\x01 \x01(\v2%.migration.v1.MigrationCapability.RPCH\x00R\x03rpc\x1a5\n" +
	"\x03RPC\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.migration.v1.MigrateTypesR\x04typeB\x06\n" +
	"\x04type\"g\n" +
	"\x1eGetMigrationCapabilityResponse\x12E\n" +
	"\fcapabilities\x18\x01 \x03(\v2!.migration.v1.MigrationCapabilityR\fcapabilities\"\xf7\x01\n" +
	"\x06Volume\x12%\n" +
	"\x0ecapacity_bytes\x18\x01 \x01(\x03R\rcapacityBytes\x12\x1b\n" +
	"\tvolume_id\x18\x02 \x01(\tR\bvolumeId\x12\x17\n" +
	"\afs_type\x18\x03 \x01(\tR\x06fsType\x12N\n" +
	"\x0evolume_context\x18\x04 \x03(\v2'.migration.v1.Volume.VolumeContextEntryR\rvolumeContext\x1a@\n" +
	"\x12VolumeContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x96\x04\n" +
	"\x14VolumeMigrateRequest\x12#\n" +
	"\rvolume_handle\x18\x01 \x01(\tR\fvolumeHandle\x12#\n" +
	"\rstorage_class\x18\x02 \x01(\tR\fstorageClass\x120\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1a.migration.v1.MigrateTypesH\x00R\x04type\x12Y\n" +
	"\rsc_parameters\x18\x04 \x03(\v24.migration.v1.VolumeMigrateRequest.ScParametersEntryR\fscParameters\x12k\n" +
	"\x13scSource_parameters\x18\x05 \x03(\v2:.migration.v1.VolumeMigrateRequest.ScSourceParametersEntryR\x12scSourceParameters\x12!\n" +
	"\fshould_clone\x18\x06 \x01(\bR\vshouldClone\x1a?\n" +
	"\x11ScParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aE\n" +
	"\x17ScSourceParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0f\n" +
	"\rmigrate_types\"V\n" +
	"\x15VolumeMigrateResponse\x12=\n" +
	"\x0fmigrated_volume\x18\x01 \x01(\v2\x14.migration.v1.VolumeR\x0emigratedVolume\"\xe7\x01\n" +
	"\x13ArrayMigrateRequest\x12.\n" +
	"\x06action\x18\x03 \x01(\v2\x14.migration.v1.ActionH\x00R\x06action\x12Q\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v21.migration.v1.ArrayMigrateRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0e\n" +
	"\faction_types\"p\n" +
	"\x14ArrayMigrateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12.\n" +
	"\x06action\x18\x02 \x01(\v2\x14.migration.v1.ActionH\x00R\x06actionB\x0e\n" +
	"\faction_types\"N\n" +
	"\x10SupportedActions\x12/\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.migration.v1.ActionTypesH\x00R\x04typeB\t\n" +
	"\aActions\"F\n" +
	"\x06Action\x12<\n" +
	"\faction_types\x18\x01 \x01(\x0e2\x19.migration.v1.ActionTypesR\vactionTypes*d\n" +
	"\fMigrateTypes\x12\x13\n" +
	"\x0fUNKNOWN_MIGRATE\x10\x00\x12\x14\n" +
	"\x10NON_REPL_TO_REPL\x10\x01\x12\x14\n" +
	"\x10REPL_TO_NON_REPL\x10\x02\x12\x13\n" +
	"\x0fVERSION_UPGRADE\x10\x03*O\n" +
	"\vActionTypes\x12\x12\n" +
	"\x0eUNKNOWN_ACTION\x10\x00\x12\x0e\n" +
	"\n" +
	"MG_MIGRATE\x10\x01\x12\r\n" +
	"\tMG_RESCAN\x10\x02\x12\r\n" +
	"\tMG_COMMIT\x10\x032\x95\x03\n" +
	"\tMigration\x12Z\n" +
	"\x0fProbeController\x12!.common.v1.ProbeControllerRequest\x1a\".common.v1.ProbeControllerResponse\"\x00\x12Z\n" +
	"\rVolumeMigrate\x12\".migration.v1.VolumeMigrateRequest\x1a#.migration.v1.VolumeMigrateResponse\"\x00\x12W\n" +
	"\fArrayMigrate\x12!.migration.v1.ArrayMigrateRequest\x1a\".migration.v1.ArrayMigrateResponse\"\x00\x12w\n" +
	"\x18GetMigrationCapabilities\x12+.migration.v1.GetMigrationCapabilityRequest\x1a,.migration.v1.GetMigrationCapabilityResponse\"\x00B\x0eZ\f./;migrationb\x06proto3"

var (
	file_migration_proto_rawDescOnce sync.Once
	file_migration_proto_rawDescData []byte
)

func file_migration_proto_rawDescGZIP() []byte {
	file_migration_proto_rawDescOnce.Do(func() {
		file_migration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_migration_proto_rawDesc), len(file_migration_proto_rawDesc)))
	})
	return file_migration_proto_rawDescData
}

var file_migration_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_migration_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_migration_proto_goTypes = []any{
	(MigrateTypes)(0),                      // 0: migration.v1.MigrateTypes
	(ActionTypes)(0),                       // 1: migration.v1.ActionTypes
	(*GetMigrationCapabilityRequest)(nil),  // 2: migration.v1.GetMigrationCapabilityRequest
	(*MigrationCapability)(nil),            // 3: migration.v1.MigrationCapability
	(*GetMigrationCapabilityResponse)(nil), // 4: migration.v1.GetMigrationCapabilityResponse
	(*Volume)(nil),                         // 5: migration.v1.Volume
	(*VolumeMigrateRequest)(nil),           // 6: migration.v1.VolumeMigrateRequest
	(*VolumeMigrateResponse)(nil),          // 7: migration.v1.VolumeMigrateResponse
	(*ArrayMigrateRequest)(nil),            // 8: migration.v1.ArrayMigrateRequest
	(*ArrayMigrateResponse)(nil),           // 9: migration.v1.ArrayMigrateResponse
	(*SupportedActions)(nil),               // 10: migration.v1.SupportedActions
	(*Action)(nil),                         // 11: migration.v1.Action
	(*MigrationCapability_RPC)(nil),        // 12: migration.v1.MigrationCapability.RPC
	nil,                                    // 13: migration.v1.Volume.VolumeContextEntry
	nil,                                    // 14: migration.v1.VolumeMigrateRequest.ScParametersEntry
	nil,                                    // 15: migration.v1.VolumeMigrateRequest.ScSourceParametersEntry
	nil,                                    // 16: migration.v1.ArrayMigrateRequest.ParametersEntry
	(*common.ProbeControllerRequest)(nil),  // 17: common.v1.ProbeControllerRequest
	(*common.ProbeControllerResponse)(nil), // 18: common.v1.ProbeControllerResponse
}
var file_migration_proto_depIdxs = []int32{
	12, // 0: migration.v1.MigrationCapability.rpc:type_name -> migration.v1.MigrationCapability.RPC
	3,  // 1: migration.v1.GetMigrationCapabilityResponse.capabilities:type_name -> migration.v1.MigrationCapability
	13, // 2: migration.v1.Volume.volume_context:type_name -> migration.v1.Volume.VolumeContextEntry
	0,  // 3: migration.v1.VolumeMigrateRequest.type:type_name -> migration.v1.MigrateTypes
	14, // 4: migration.v1.VolumeMigrateRequest.sc_parameters:type_name -> migration.v1.VolumeMigrateRequest.ScParametersEntry
	15, // 5: migration.v1.VolumeMigrateRequest.scSource_parameters:type_name -> migration.v1.VolumeMigrateRequest.ScSourceParametersEntry
	5,  // 6: migration.v1.VolumeMigrateResponse.migrated_volume:type_name -> migration.v1.Volume
	11, // 7: migration.v1.ArrayMigrateRequest.action:type_name -> migration.v1.Action
	16, // 8: migration.v1.ArrayMigrateRequest.parameters:type_name -> migration.v1.ArrayMigrateRequest.ParametersEntry
	11, // 9: migration.v1.ArrayMigrateResponse.action:type_name -> migration.v1.Action
	1,  // 10: migration.v1.SupportedActions.type:type_name -> migration.v1.ActionTypes
	1,  // 11: migration.v1.Action.action_types:type_name -> migration.v1.ActionTypes
	0,  // 12: migration.v1.MigrationCapability.RPC.type:type_name -> migration.v1.MigrateTypes
	17, // 13: migration.v1.Migration.ProbeController:input_type -> common.v1.ProbeControllerRequest
	6,  // 14: migration.v1.Migration.VolumeMigrate:input_type -> migration.v1.VolumeMigrateRequest
	8,  // 15: migration.v1.Migration.ArrayMigrate:input_type -> migration.v1.ArrayMigrateRequest
	2,  // 16: migration.v1.Migration.GetMigrationCapabilities:input_type -> migration.v1.GetMigrationCapabilityRequest
	18, // 17: migration.v1.Migration.ProbeController:output_type -> common.v1.ProbeControllerResponse
	7,  // 18: migration.v1.Migration.VolumeMigrate:output_type -> migration.v1.VolumeMigrateResponse
	9,  // 19: migration.v1.Migration.ArrayMigrate:output_type -> migration.v1.ArrayMigrateResponse
	4,  // 20: migration.v1.Migration.GetMigrationCapabilities:output_type -> migration.v1.GetMigrationCapabilityResponse
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_migration_proto_init() }
func file_migration_proto_init() {
	if File_migration_proto != nil {
		return
	}
	file_migration_proto_msgTypes[1].OneofWrappers = []any{
		(*MigrationCapability_Rpc)(nil),
	}
	file_migration_proto_msgTypes[4].OneofWrappers = []any{
		(*VolumeMigrateRequest_Type)(nil),
	}
	file_migration_proto_msgTypes[6].OneofWrappers = []any{
		(*ArrayMigrateRequest_Action)(nil),
	}
	file_migration_proto_msgTypes[7].OneofWrappers = []any{
		(*ArrayMigrateResponse_Action)(nil),
	}
	file_migration_proto_msgTypes[8].OneofWrappers = []any{
		(*SupportedActions_Type)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_migration_proto_rawDesc), len(file_migration_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_migration_proto_goTypes,
		DependencyIndexes: file_migration_proto_depIdxs,
		EnumInfos:         file_migration_proto_enumTypes,
		MessageInfos:      file_migration_proto_msgTypes,
	}.Build()
	File_migration_proto = out.File
	file_migration_proto_goTypes = nil
	file_migration_proto_depIdxs = nil
}
