// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProbeControllerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeControllerRequest) Reset() {
	*x = ProbeControllerRequest{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeControllerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeControllerRequest) ProtoMessage() {}

func (x *ProbeControllerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeControllerRequest.ProtoReflect.Descriptor instead.
func (*ProbeControllerRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

// Metadata about the driver
// for accepting the RPC calls
type ProbeControllerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the driver
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Version of CSI driver
	VendorVersion string                `protobuf:"bytes,2,opt,name=vendor_version,json=vendorVersion,proto3" json:"vendor_version,omitempty"`
	Manifest      map[string]string     `protobuf:"bytes,3,rep,name=manifest,proto3" json:"manifest,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ready         *wrapperspb.BoolValue `protobuf:"bytes,4,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeControllerResponse) Reset() {
	*x = ProbeControllerResponse{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeControllerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeControllerResponse) ProtoMessage() {}

func (x *ProbeControllerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeControllerResponse.ProtoReflect.Descriptor instead.
func (*ProbeControllerResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *ProbeControllerResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProbeControllerResponse) GetVendorVersion() string {
	if x != nil {
		return x.VendorVersion
	}
	return ""
}

func (x *ProbeControllerResponse) GetManifest() map[string]string {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *ProbeControllerResponse) GetReady() *wrapperspb.BoolValue {
	if x != nil {
		return x.Ready
	}
	return nil
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\tcommon.v1\x1a\x1egoogle/protobuf/wrappers.proto\"\x18\n" +
	"\x16ProbeControllerRequest\"\x91\x02\n" +
	"\x17ProbeControllerResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0evendor_version\x18\x02 \x01(\tR\rvendorVersion\x12L\n" +
	"\bmanifest\x18\x03 \x03(\v20.common.v1.ProbeControllerResponse.ManifestEntryR\bmanifest\x120\n" +
	"\x05ready\x18\x04 \x01(\v2\x1a.google.protobuf.BoolValueR\x05ready\x1a;\n" +
	"\rManifestEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B,Z*github.com/dell/dell-csi-extensions/commonb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_proto_goTypes = []any{
	(*ProbeControllerRequest)(nil),  // 0: common.v1.ProbeControllerRequest
	(*ProbeControllerResponse)(nil), // 1: common.v1.ProbeControllerResponse
	nil,                             // 2: common.v1.ProbeControllerResponse.ManifestEntry
	(*wrapperspb.BoolValue)(nil),    // 3: google.protobuf.BoolValue
}
var file_common_proto_depIdxs = []int32{
	2, // 0: common.v1.ProbeControllerResponse.manifest:type_name -> common.v1.ProbeControllerResponse.ManifestEntry
	3, // 1: common.v1.ProbeControllerResponse.ready:type_name -> google.protobuf.BoolValue
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
