// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: podmon.proto

package podmon

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ValidateVolumeHostConnectivityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The IDs of the volumes that are used on the specified node.
	// This field is REQUIRED.
	VolumeIds []string `protobuf:"bytes,1,rep,name=volume_ids,json=volumeIds,proto3" json:"volume_ids,omitempty"`
	// The ID of the node. This field is REQUIRED. The CO SHALL set this
	// field to match the node ID returned by `NodeGetInfo`.
	NodeId string `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// The array ID used to query connectivity to the node.
	// All the volume_ids if specified should blong to this array id.
	ArrayId string `protobuf:"bytes,4,opt,name=array_id,json=arrayId,proto3" json:"array_id,omitempty"`
	// The length of time in seconds to sample for I/O activity
	IoSampleTimeSeconds int32 `protobuf:"varint,3,opt,name=io_sample_time_seconds,json=ioSampleTimeSeconds,proto3" json:"io_sample_time_seconds,omitempty"`
}

func (x *ValidateVolumeHostConnectivityRequest) Reset() {
	*x = ValidateVolumeHostConnectivityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_podmon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateVolumeHostConnectivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateVolumeHostConnectivityRequest) ProtoMessage() {}

func (x *ValidateVolumeHostConnectivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podmon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateVolumeHostConnectivityRequest.ProtoReflect.Descriptor instead.
func (*ValidateVolumeHostConnectivityRequest) Descriptor() ([]byte, []int) {
	return file_podmon_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateVolumeHostConnectivityRequest) GetVolumeIds() []string {
	if x != nil {
		return x.VolumeIds
	}
	return nil
}

func (x *ValidateVolumeHostConnectivityRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ValidateVolumeHostConnectivityRequest) GetArrayId() string {
	if x != nil {
		return x.ArrayId
	}
	return ""
}

func (x *ValidateVolumeHostConnectivityRequest) GetIoSampleTimeSeconds() int32 {
	if x != nil {
		return x.IoSampleTimeSeconds
	}
	return 0
}

type ValidateVolumeHostConnectivityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The host is currently connected.
	Connected bool `protobuf:"varint,1,opt,name=connected,proto3" json:"connected,omitempty"`
	// I/Os have been overserved recently.
	IosInProgress bool `protobuf:"varint,2,opt,name=ios_in_progress,json=iosInProgress,proto3" json:"ios_in_progress,omitempty"`
	// General status messages.
	Messages []string `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *ValidateVolumeHostConnectivityResponse) Reset() {
	*x = ValidateVolumeHostConnectivityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_podmon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateVolumeHostConnectivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateVolumeHostConnectivityResponse) ProtoMessage() {}

func (x *ValidateVolumeHostConnectivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_podmon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateVolumeHostConnectivityResponse.ProtoReflect.Descriptor instead.
func (*ValidateVolumeHostConnectivityResponse) Descriptor() ([]byte, []int) {
	return file_podmon_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateVolumeHostConnectivityResponse) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *ValidateVolumeHostConnectivityResponse) GetIosInProgress() bool {
	if x != nil {
		return x.IosInProgress
	}
	return false
}

func (x *ValidateVolumeHostConnectivityResponse) GetMessages() []string {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_podmon_proto protoreflect.FileDescriptor

var file_podmon_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x6f, 0x64, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09,
	0x70, 0x6f, 0x64, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x22, 0xaf, 0x01, 0x0a, 0x25, 0x56, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x48, 0x6f, 0x73, 0x74,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x5f, 0x69, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x49,
	0x64, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61,
	0x72, 0x72, 0x61, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x72, 0x72, 0x61, 0x79, 0x49, 0x64, 0x12, 0x33, 0x0a, 0x16, 0x69, 0x6f, 0x5f, 0x73, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x13, 0x69, 0x6f, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x22, 0x8a, 0x01, 0x0a, 0x26,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x48, 0x6f,
	0x73, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x65, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x69, 0x6f, 0x73, 0x5f, 0x69, 0x6e, 0x5f, 0x70,
	0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x69,
	0x6f, 0x73, 0x49, 0x6e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x32, 0x92, 0x01, 0x0a, 0x06, 0x50, 0x6f, 0x64,
	0x6d, 0x6f, 0x6e, 0x12, 0x87, 0x01, 0x0a, 0x1e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x12, 0x30, 0x2e, 0x70, 0x6f, 0x64, 0x6d, 0x6f, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x56, 0x6f, 0x6c, 0x75, 0x6d,
	0x65, 0x48, 0x6f, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x70, 0x6f, 0x64, 0x6d, 0x6f,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x56, 0x6f, 0x6c,
	0x75, 0x6d, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a,
	0x08, 0x2e, 0x3b, 0x70, 0x6f, 0x64, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_podmon_proto_rawDescOnce sync.Once
	file_podmon_proto_rawDescData = file_podmon_proto_rawDesc
)

func file_podmon_proto_rawDescGZIP() []byte {
	file_podmon_proto_rawDescOnce.Do(func() {
		file_podmon_proto_rawDescData = protoimpl.X.CompressGZIP(file_podmon_proto_rawDescData)
	})
	return file_podmon_proto_rawDescData
}

var file_podmon_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_podmon_proto_goTypes = []interface{}{
	(*ValidateVolumeHostConnectivityRequest)(nil),  // 0: podmon.v1.ValidateVolumeHostConnectivityRequest
	(*ValidateVolumeHostConnectivityResponse)(nil), // 1: podmon.v1.ValidateVolumeHostConnectivityResponse
}
var file_podmon_proto_depIdxs = []int32{
	0, // 0: podmon.v1.Podmon.ValidateVolumeHostConnectivity:input_type -> podmon.v1.ValidateVolumeHostConnectivityRequest
	1, // 1: podmon.v1.Podmon.ValidateVolumeHostConnectivity:output_type -> podmon.v1.ValidateVolumeHostConnectivityResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_podmon_proto_init() }
func file_podmon_proto_init() {
	if File_podmon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_podmon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateVolumeHostConnectivityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_podmon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateVolumeHostConnectivityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_podmon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_podmon_proto_goTypes,
		DependencyIndexes: file_podmon_proto_depIdxs,
		MessageInfos:      file_podmon_proto_msgTypes,
	}.Build()
	File_podmon_proto = out.File
	file_podmon_proto_rawDesc = nil
	file_podmon_proto_goTypes = nil
	file_podmon_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PodmonClient is the client API for Podmon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PodmonClient interface {
	// ValidateVolumeHostconnectivity validates host connectivity for one or more volumes, by
	// either or both of two methds:
	// 1. Verifying the link status of the host, returned in the connected.
	// 2. Verifying if any I/O activity has been observerd in the recent past, returned in ios_in_progress.
	ValidateVolumeHostConnectivity(ctx context.Context, in *ValidateVolumeHostConnectivityRequest, opts ...grpc.CallOption) (*ValidateVolumeHostConnectivityResponse, error)
}

type podmonClient struct {
	cc grpc.ClientConnInterface
}

func NewPodmonClient(cc grpc.ClientConnInterface) PodmonClient {
	return &podmonClient{cc}
}

func (c *podmonClient) ValidateVolumeHostConnectivity(ctx context.Context, in *ValidateVolumeHostConnectivityRequest, opts ...grpc.CallOption) (*ValidateVolumeHostConnectivityResponse, error) {
	out := new(ValidateVolumeHostConnectivityResponse)
	err := c.cc.Invoke(ctx, "/podmon.v1.Podmon/ValidateVolumeHostConnectivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PodmonServer is the server API for Podmon service.
type PodmonServer interface {
	// ValidateVolumeHostconnectivity validates host connectivity for one or more volumes, by
	// either or both of two methds:
	// 1. Verifying the link status of the host, returned in the connected.
	// 2. Verifying if any I/O activity has been observerd in the recent past, returned in ios_in_progress.
	ValidateVolumeHostConnectivity(context.Context, *ValidateVolumeHostConnectivityRequest) (*ValidateVolumeHostConnectivityResponse, error)
}

// UnimplementedPodmonServer can be embedded to have forward compatible implementations.
type UnimplementedPodmonServer struct {
}

func (*UnimplementedPodmonServer) ValidateVolumeHostConnectivity(context.Context, *ValidateVolumeHostConnectivityRequest) (*ValidateVolumeHostConnectivityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateVolumeHostConnectivity not implemented")
}

func RegisterPodmonServer(s *grpc.Server, srv PodmonServer) {
	s.RegisterService(&_Podmon_serviceDesc, srv)
}

func _Podmon_ValidateVolumeHostConnectivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateVolumeHostConnectivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodmonServer).ValidateVolumeHostConnectivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/podmon.v1.Podmon/ValidateVolumeHostConnectivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodmonServer).ValidateVolumeHostConnectivity(ctx, req.(*ValidateVolumeHostConnectivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Podmon_serviceDesc = grpc.ServiceDesc{
	ServiceName: "podmon.v1.Podmon",
	HandlerType: (*PodmonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateVolumeHostConnectivity",
			Handler:    _Podmon_ValidateVolumeHostConnectivity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "podmon.proto",
}
